# Generated by Django 4.0.3 on 2022-04-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0003_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='telegram',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
