# Generated by Django 4.0.3 on 2022-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0004_alter_userdetail_telegram_alter_userdetail_whatsapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('date', 'time'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': 'Детали', 'verbose_name_plural': 'Детали'},
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='telegram_acc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='theme',
            field=models.CharField(blank=True, default='Консультация', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
