# Generated by Django 4.0.3 on 2022-04-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0005_alter_lesson_options_alter_userdetail_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='telegram_acc',
            new_name='telegram',
        ),
    ]
