# Generated by Django 4.0.3 on 2022-04-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0007_remove_lesson_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='discord',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='high_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='skype',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='usual_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
