# Generated by Django 4.0.3 on 2022-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0009_alter_userdetail_high_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'TimeBlock',
                'verbose_name_plural': 'Timeblocks',
                'ordering': ('date', 'start_time'),
            },
        ),
    ]
