# Generated by Django 4.0.3 on 2022-08-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_app', '0010_timeblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeblock',
            options={'ordering': ('date', 'start_time'), 'verbose_name': 'Блокировщик времени', 'verbose_name_plural': 'Блокировщик времени'},
        ),
    ]
